# @content/meta.yml
site:
  title: Strata
  description: Infrastructure for operational excellence
  url: 'https://www.strata.ng'
  logo:
    src: https://cdn.strata.ng/logo.png
    alt: Strata logo
  pattern:
    src: https://cdn.strata.ng/pattern.png
    alt: Strata pebbles pattern
  legalName: Strata Advisory Limited
  declaration: All rights reserved.  